    /* WHILE ->  ENQUANTO (WHILE) A CONDIÇÃO FOR VERDADE , EXECUTE O CÓDIGO 
    EX ABAIXO ELE VAIEXECUTAR O CÓDIGO   NA LINHA ATIVANDO O LOOP COM O WHILE 
    E LOGO DEPOIS ENTRE CHAVES COLOCA DENTRO A CONDIÇÃO 
    ( ENQUANTO O NÚMERO FOR MAIOR QUE 10)E QUEM VAI EXECUTAR
    A ORDEM LOGO DEPOIS ENTRE CHAVES NA SEGUNDA LINHA USAMOS  O CONSOLE.LOG  
     E ENTRE PARENTES */

    

let  num = 1;


while(num < 10){
    console.log("Número:"+ num);
    num = num + 2;
}
